spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_series_database
    username: root
    password: Login@mysql123


  jpa:
    hibernate:
      ddl-auto: update


  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8085
